# Generated by Django 3.2 on 2021-05-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('permit_conditions', models.TextField()),
                ('permit_authority', models.CharField(max_length=200)),
                ('site', models.CharField(choices=[('Gay', 'Gaydon'), ('W1', 'Wellesbourne Unit 1'), ('W2', 'Wellesbourne Unit 2'), ('SA', 'St. Athan'), ('WO', 'Wolverton Mill'), ('NP', 'Newport Pagnell')], max_length=3)),
                ('area', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
