# Generated by Django 3.2 on 2021-05-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit_tracker', '0002_auto_20210503_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
